import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider, SignIn } from '@clerk/nextjs'
import { SignedIn} from '@clerk/nextjs'
import { SignedOut } from '@clerk/nextjs'
import {Playpen_Sans} from 'next/font/google'
import Navbar from '@/components/Navbar'
const inter = Playpen_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <ClerkProvider>
      <html lang="en">
         
          <body className={inter.className}>
          <SignedIn>
              <Navbar />
                {children}
          </SignedIn>
          <SignedOut>
            <SignIn/>
          </SignedOut>
          </body>
          </html>
      </ClerkProvider>
  )
}


