import type { Metadata } from 'next'
import './globals.css'

import { ClerkProvider, SignIn, currentUser } from '@clerk/nextjs'
import { SignedIn} from '@clerk/nextjs'
import { SignedOut } from '@clerk/nextjs'
import {Playpen_Sans} from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
const inter = Playpen_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  
  const user = await currentUser();
  return (
        <ClerkProvider>
      <html lang="en">
         
          <body className={inter.className}>
          <SignedIn>
              <Navbar />
            {children}
            
              <Footer />
            <div>Hello {user?.firstName}</div>;
          </SignedIn>
          <SignedOut>
            <SignIn/>
          </SignedOut>
          </body>
          </html>
      </ClerkProvider>
  )
}


